In [4]:
import numpy as np

In [82]:
with open("example.txt") as f:
    data = f.read()

In [113]:
with open("input.txt") as f:
    data = f.read()

In [114]:
board = []
lines = data.strip().split("\n")
for i in range(len(lines)):
    board.append([])
    for j in range(len(lines[i])):
        board[i].append(lines[i][j])
        

In [115]:
b = np.array(board)

In [116]:
seen = np.zeros(b.shape)

In [117]:
seen[0,:] = 1
seen[:,0] = 1
seen[-1,:] = 1
seen[:,-1] = 1

In [118]:
# from left
for i in range(0,b.shape[0]):
    h = b[i,0]
    for j in range(1,b.shape[1]):
        if b[i,j] > h:
            seen[i,j] = 1
            h = b[i,j]
        #print(i,j)

# 1,1 1,2 1,3
# 2,1 2,2 2,3
# 3,1 3,2 3,3
        
# from right
for i in range(0,b.shape[0]):
    h = b[i,-1]
    for j in range(b.shape[1]-1,0,-1):
        if b[i,j] > h:
            seen[i,j] = 1
            h = b[i,j]

# from top
for i in range(0,b.shape[0]):
    h = b[0,i]
    for j in range(0,b.shape[1]):
        if b[j,i] > h:
            seen[j,i] = 1
            h = b[j,i]

# from bottom
for i in range(0,b.shape[0]):
    h = b[-1,i]
    for j in range(b.shape[1]-1,0,-1):
        if b[j,i] > h:
            seen[j,i] = 1
            h = b[j,i]



In [119]:
print(seen)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [120]:
sum(sum(seen))
# guessed 1349

1843.0

In [123]:
def findSenicValue(board,x,y):
    i,j = x,y
    vals = 1
    for direction in [(0,1),(0,-1),(1,0),(-1,0)]:
        treeHeight = board[x,y]
        i,j = x,y
        i += direction[0]
        j += direction[1]
        found = 0
        while (found == 0
            and 0 <= i and i < board.shape[0] 
            and 0 <= j and j < board.shape[1]):
            if board[i,j] >= treeHeight:
                val = abs(i-x) + abs(j-y)
                #print("found val")
                #print(i,j,x,y,val)
                vals *= val
                found = 1
            i += direction[0]
            j += direction[1]
        if found == 0:
            #print(i,j,x,y,val)
            #print("got to end")
            i -= direction[0]
            j -= direction[1]
            val = abs(i-x) + abs(j-y)
            #print(i,j,x,y,val)
            vals *= abs(i-x) + abs(j-y)
    return vals
            
maxVal = 0
valLoc = (0,0)
for i in range(0,b.shape[0]):
    for j in range(0,b.shape[1]):
        #print("maxVal is",maxVal)
        v = findSenicValue(b,i,j)
        if v > maxVal:
            maxVal = v
            valLoc = (i,j)
print(findSenicValue(b,3,2))

1


In [124]:
print(maxVal)

180000


In [127]:
print(valLoc)

(50, 15)


In [128]:
findSenicValue(b,50,15)

180000

In [129]:
180000**.25

20.597671439071178