In [1]:
import re
import numpy as np
import math
from matplotlib import pyplot as plt
from collections import defaultdict

In [94]:
with open("example.txt") as f:
    data = f.read()
    lines = data.strip().split("\n")
    records = data.strip().split("\n\n")

In [100]:
with open("input.txt") as f:
    data = f.read()
    lines = data.strip().split("\n")   
    records = data.strip().split("\n\n")

In [101]:
#board = np.array([list(x) for x in lines])
#plt.matshow(screen)

In [102]:
board = []
for line in lines:
    board.append([1 if x == "#" else 0 for x in line])
board = np.array(board)
print(board)

[[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


In [103]:
def print_board(points):
    maxy,miny,maxx,minx = 0,0,0,0
    for point in points:
        maxy = max(maxy,point[0])
        maxx = max(maxx,point[1])
        miny = min(miny,point[0])
        minx = min(minx,point[1])
    print((maxy-miny),(maxx-minx))
    print(len(points))
    example_board = np.zeros(((maxy-miny+1),(maxx-minx+1)))
    for point in points:
        example_board[point[0]-miny,point[1]-minx] = 1
    print(example_board)

In [105]:
dirs_index = [(-1,0),(1,0),(0,-1),(0,1)]
dirs = {(-1,0):[(-1,-1),(-1,0),(-1,1)],(1,0):[(1,-1),(1,0),(1,1)],(0,-1):[(-1,-1),(0,-1),(1,-1)],(0,1):[(-1,1),(0,1),(1,1)]}
locations = np.where(board==1)
points = [(x,y) for x,y in zip(locations[0],locations[1])]
print(len(points))
points = set(points)
for i in range(100000):
    new_points = {}
    for point in points:
        elfFound = False
        new_point = None
        for d in dirs_index:
            checks = dirs[d]
            directionGood = True
            for check in checks:
                #print(point,check)
                tmp_point = (point[0]+check[0],point[1]+check[1])
                if tmp_point in points:
                    directionGood = False
                    elfFound = True
            if new_point == None and directionGood == True:
                new_point = (point[0]+d[0],point[1]+d[1])

        if elfFound and new_point is not None:
            if new_point not in new_points:
                new_points[new_point] = [point]
            else:
                # thus both points will not actually be updated, we'll take care of that below
                new_points[new_point].append(point)
        else:
            new_points[point] = [point]
    
    checked_new_points = set()
    for new_point,old_points in new_points.items():
        if len(old_points) == 1:
            checked_new_points.add(new_point)
        else:
            for old_point in old_points:
                checked_new_points.add(old_point)
    
    if (points == checked_new_points):
        print("Part 2: simulation ended at round",i+1)
        break
    points = checked_new_points
    dirs_index = dirs_index[1:]+[dirs_index[0]]
    #print_board(points)

2715
Part 2: simulation ended at round 1036


In [92]:
maxy,miny,maxx,minx = 0,0,0,0
for point in points:
    maxy = max(maxy,point[0])
    maxx = max(maxx,point[1])
    miny = min(miny,point[0])
    minx = min(minx,point[1])
print((maxy-miny),(maxx-minx))
print(len(points))
print("p1",(maxy-miny+1)*(maxx-minx+1)-len(points))
print_board(points)

82 81
2715
p1 4091
82 81
2715
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [43]:
end_example = """......#.....
..........#.
.#.#..#.....
.....#......
..#.....#..#
#......##...
....##......
.#........#.
...#.#..#...
............
...#..#..#.."""

In [46]:
len(end_example.split("\n"))
len(end_example.split("\n")[0])

12