In [1]:
import re
import numpy as np
import math
from matplotlib import pyplot as plt

In [42]:
with open("example.txt") as f:
    data = f.read()
    lines = data.strip().split("\n")
    records = data.strip().split("\n\n")

In [43]:
with open("input.txt") as f:
    data = f.read()
    lines = data.strip().split("\n")   
    records = data.strip().split("\n\n")

In [44]:
#board = np.array([list(x) for x in lines])
#plt.matshow(screen)

In [45]:
#>>.<^<#
#.<..<<#
#>v.><>#
#<^v^^>#
dirs = {">":0,"v":1,"<":2,"^":3,"#":-1,".":-2}
init_snow_storms = {}
board = []
for line in lines:
    tmp = []
    for char in line:
        tmp.append(dirs[char])
    board.append(tmp)
board = np.array(board)
for i in range(4):
    init_snow_storms[i] = np.zeros(board.shape)
    init_snow_storms[i][board==i] = 1
walls = np.zeros(board.shape)
walls[board==-1] = 1

In [46]:
print(init_snow_storms)

{0: array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 1: array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 2: array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 3: array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])}


In [47]:
print(init_snow_storms[0])
tmp = np.roll(init_snow_storms[0],1,axis=1)
tmp[:,1] = tmp[:,-1]
tmp[:,-1] = 0
# print(tmp)
# print("snow 0")
# print(snow_storms[0])
# print(roll_one(snow_storms[0],1,1,1,-1))
# print("snow 1")
# print(snow_storms[1])
# print(roll_one(snow_storms[1],0,1,1,-1))
# print("snow 2")
# print(snow_storms[2])
# print(roll_one(snow_storms[2],1,-1,-2,0))
# print("snow 3")
# print(snow_storms[3])
# print(roll_one(snow_storms[3],0,-1,-2,0))

dirs = {">":0,"v":1,"<":2,"^":3,"#":-1,".":-2}

def roll_one(array,axis,amount,start,end):
    tmp = np.roll(array,amount,axis=axis)
    if axis == 1:
        tmp[:,start] = tmp[:,end]
        tmp[:,end] = 0
    elif axis == 0:
        tmp[start,:] = tmp[end,:]
        tmp[end,:] = 0
    return tmp

def update_snow_storms(snow_storms):
    new_snow_storms = {}
    new_snow_storms[0] = roll_one(snow_storms[0],1,1,1,-1)
    new_snow_storms[1] = roll_one(snow_storms[1],0,1,1,-1)
    new_snow_storms[2] = roll_one(snow_storms[2],1,-1,-2,0)
    new_snow_storms[3] = roll_one(snow_storms[3],0,-1,-2,0)
    return new_snow_storms

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [48]:
found_end = False
initial_board = init_snow_storms[0] + init_snow_storms[1] + init_snow_storms[2] + init_snow_storms[3] + walls
snow_storms = init_snow_storms
print(initial_board)
start = np.where(initial_board[:,:] == 0)
print(start)
start_t = (start[0][0],start[1][0])
points = set([(start[0][0],start[1][0])])
print("starting at ",points)
end = np.where(initial_board[:,:] == 0)
end_point = (end[0][-1],end[1][-1])
print("ending at",end_point)
round_count = 0
while not found_end:
    snow_storms = update_snow_storms(snow_storms)
    
    current_board = snow_storms[0] + snow_storms[1] + snow_storms[2] + snow_storms[3] + walls
    #print(current_board)
    new_points = set()
    for point in points:
        for d in [(0,0),(-1,0),(1,0),(0,-1),(0,1)]:
            new_point = (d[0]+point[0],d[1]+point[1])
            if new_point[0] == end_point[0] and new_point[1] == end_point[1]:
                found_end = True
            if current_board[new_point] == 0:
                new_points.add(new_point)
    
    points = new_points
    print("round is",round_count)
    print("next round has",len(points),"point(s)")
    round_count += 1
print(round_count)

[[1. 0. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]]
(array([ 0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
       11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 18, 18,
       18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19,

In [49]:
# back track for lunch
start_t = (start[0][0],start[1][0])
end_t = (end[0][-1],end[1][-1])
points = set([end_t])
print("starting at ",points)
end_point = (start_t)
found_end = False
# round_count = 0

while not found_end:
    snow_storms = update_snow_storms(snow_storms)
    
    current_board = snow_storms[0] + snow_storms[1] + snow_storms[2] + snow_storms[3] + walls
    #print(current_board)
    new_points = set()
    for point in points:
        for d in [(0,0),(-1,0),(1,0),(0,-1),(0,1)]:
            new_point = (d[0]+point[0],d[1]+point[1])
            if new_point[0] == end_point[0] and new_point[1] == end_point[1]:
                found_end = True
            if new_point[0] < current_board.shape[0] and new_point[1] < current_board.shape[1] and current_board[new_point] == 0:
                new_points.add(new_point)
    
    points = new_points
    print("round is",round_count)
    print("next round has",len(points),"point(s)")
    round_count += 1

starting at  {(36, 100)}
round is 240
next round has 2 point(s)
round is 241
next round has 3 point(s)
round is 242
next round has 3 point(s)
round is 243
next round has 4 point(s)
round is 244
next round has 7 point(s)
round is 245
next round has 9 point(s)
round is 246
next round has 10 point(s)
round is 247
next round has 10 point(s)
round is 248
next round has 14 point(s)
round is 249
next round has 9 point(s)
round is 250
next round has 13 point(s)
round is 251
next round has 15 point(s)
round is 252
next round has 14 point(s)
round is 253
next round has 13 point(s)
round is 254
next round has 14 point(s)
round is 255
next round has 18 point(s)
round is 256
next round has 17 point(s)
round is 257
next round has 21 point(s)
round is 258
next round has 26 point(s)
round is 259
next round has 29 point(s)
round is 260
next round has 34 point(s)
round is 261
next round has 33 point(s)
round is 262
next round has 38 point(s)
round is 263
next round has 43 point(s)
round is 264
next roun

In [50]:
# and finish
start_t = (start[0][0],start[1][0])
end_t = (end[0][-1],end[1][-1])
points = set([start_t])
print("starting at ",points)
end_point = (end_t)
found_end = False
# round_count = 0

while not found_end:
    snow_storms = update_snow_storms(snow_storms)
    
    current_board = snow_storms[0] + snow_storms[1] + snow_storms[2] + snow_storms[3] + walls
    #print(current_board)
    new_points = set()
    for point in points:
        for d in [(0,0),(-1,0),(1,0),(0,-1),(0,1)]:
            new_point = (d[0]+point[0],d[1]+point[1])
            if new_point[0] == end_point[0] and new_point[1] == end_point[1]:
                found_end = True
            if current_board[new_point] == 0:
                new_points.add(new_point)
    
    points = new_points
    print("round is",round_count)
    print("next round has",len(points),"point(s)")
    round_count += 1

starting at  {(0, 1)}
round is 477
next round has 1 point(s)
round is 478
next round has 2 point(s)
round is 479
next round has 2 point(s)
round is 480
next round has 3 point(s)
round is 481
next round has 5 point(s)
round is 482
next round has 7 point(s)
round is 483
next round has 8 point(s)
round is 484
next round has 9 point(s)
round is 485
next round has 13 point(s)
round is 486
next round has 12 point(s)
round is 487
next round has 16 point(s)
round is 488
next round has 15 point(s)
round is 489
next round has 10 point(s)
round is 490
next round has 11 point(s)
round is 491
next round has 12 point(s)
round is 492
next round has 12 point(s)
round is 493
next round has 16 point(s)
round is 494
next round has 19 point(s)
round is 495
next round has 22 point(s)
round is 496
next round has 19 point(s)
round is 497
next round has 21 point(s)
round is 498
next round has 28 point(s)
round is 499
next round has 22 point(s)
round is 500
next round has 21 point(s)
round is 501
next round ha

In [51]:
print(round_count)
# guessed 716, probably off by one
# but the code gives the right answer for the example
# huh. reran everything from the beginning, and got 717, which is right. Yay jupyter notebook and non-linear execution

717
