In [56]:
import numpy as np
import math

In [73]:
with open("input.txt") as f:
    lines = f.read().strip().split("\n")


In [32]:
with open("example.txt") as f:
    lines = f.read().strip().split("\n")


In [74]:
lines[3]

'R 2'

In [83]:
b = np.zeros([1000,1000])
points = [[50,50] for i in range(10)]
print(points)
head = points[0]
tail = points[-1]
directions = {
    "D":(-1,0),
    "U":(1,0),
    "R":(0,1),
    "L":(0,-1)
}
b[tail[0],tail[1]] = 1

for line in lines:
    direction,count = line.split()
    for _ in range(int(count)):
        points[0][0] += directions[direction][0]
        points[0][1] += directions[direction][1]
        for i in range(1,len(points)):
            dx = points[i-1][0]-points[i][0]
            dy = points[i-1][1]-points[i][1]
            sign_dx = int(dx/abs(dx)) if dx != 0 else 0
            sign_dy = int(dy/abs(dy)) if dy != 0 else 0
            if abs(dx) > 1 or abs(dy) > 1:
                if abs(dx) == abs(dy):
                    #diag
                    points[i][0] = points[i-1][0]-sign_dx
                    points[i][1] = points[i-1][1]-sign_dy
                elif abs(dx) > abs(dy):
                    points[i][0] = points[i-1][0]-sign_dx
                    points[i][1] = points[i-1][1]
                else:
                    points[i][0] = points[i-1][0]
                    points[i][1] = points[i-1][1]-sign_dy
           # print("going")
           # print(dx,dy,head,tail)
            b[tail[0],tail[1]] = 1
            #t = np.array(b)
            #t[head[0],head[1]] = 2
            #t[tail[0],tail[1]] = 3
           # print(t[49:57,49:57])


[[50, 50], [50, 50], [50, 50], [50, 50], [50, 50], [50, 50], [50, 50], [50, 50], [50, 50], [50, 50]]


In [84]:
print(head)

[173, -1]


In [85]:
print(b[40:60,40:60])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.

In [86]:
sum(sum(b))

2367.0